### ISSUE TITLE
Update Item

### ISSUE THREAD

**Issue by e-nouri** [ginger-io/beyonce#27]
Yesterday I realised that there is no update Item, and trying to implement it myself  was not straight forward, especially the conditional updates and the nested fields when you have lists and maps inside your model. On the same note as the Put ReturnValue, having the option to get the updated fields is also good.

I know you are pretty responsive and quick to add these, I realise that this feature may be the trickiest until now, Let me know if you wanna discuss it here, may be I'll make a PR.

For now I just exported the DocumentClient and made a plain update myself just to not get stuck.

**Comment by jcarver989** [comment]
Yea update is a bit interesting because it's really `updateOrCreate` (DynamoDB will create the item if you call updateItem and it doesn't exist). 

From the caller's point of view, I think you'd want a way to express a potentially nested change set on the model. For that, lenses are a very useful tool. So I'd imagine an API something like: 

```TypeScript
const key = // dynamodb key
const updateLens = XXXModel.update(key)
updateLens.foo.bar.baz.update(value => newValue) // nested field
beyonce.updateItem(lens)
```

**Comment by e-nouri** [comment]
Yes definitely, the lenses will also help when generating the attributes to update in the dynamodb request and may be the conditions if present.
